name: musicplayer
description: 'An open source radio application developed as a learning project. The project is still in development, and constructive feedback is welcome'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  file_picker: ^8.0.0
  font_awesome_flutter: ^10.12.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  collection: ^1.18.0
  flutter_localizations:
    sdk: flutter

  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo3.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/sem.jpg