// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQmN59oDsB_Jlrx7f9DrOOAt9GifTwtQ',
    appId: '1:1067650580465:web:55bee0ab91577801ea8e50',
    messagingSenderId: '1067650580465',
    projectId: 'flacradio',
    authDomain: 'flacradio.firebaseapp.com',
    storageBucket: 'flacradio.firebasestorage.app',
    measurementId: 'G-7SYVGMKQJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrGHmX8l0qY5wdN24MkjZbWrPE43Ms-g',
    appId: '1:1067650580465:android:be12bd32a29ce7cbea8e50',
    messagingSenderId: '1067650580465',
    projectId: 'flacradio',
    storageBucket: 'flacradio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7qPnQ49lZKQG9PQG5P08mhZXNiH-hNM4',
    appId: '1:1067650580465:ios:02bd9ecc50700a68ea8e50',
    messagingSenderId: '1067650580465',
    projectId: 'flacradio',
    storageBucket: 'flacradio.firebasestorage.app',
    iosBundleId: 'com.zavarkastudio.flacradio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7qPnQ49lZKQG9PQG5P08mhZXNiH-hNM4',
    appId: '1:1067650580465:ios:02bd9ecc50700a68ea8e50',
    messagingSenderId: '1067650580465',
    projectId: 'flacradio',
    storageBucket: 'flacradio.firebasestorage.app',
    iosBundleId: 'com.zavarkastudio.flacradio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeQmN59oDsB_Jlrx7f9DrOOAt9GifTwtQ',
    appId: '1:1067650580465:web:d45d5e5f6acd20a1ea8e50',
    messagingSenderId: '1067650580465',
    projectId: 'flacradio',
    authDomain: 'flacradio.firebaseapp.com',
    storageBucket: 'flacradio.firebasestorage.app',
    measurementId: 'G-B0EXGK4C2P',
  );
}
